###############################################################################
# BEETHOVEN Snakemake configuration (dev)
# 02 October 2026
# Mitchell Manware

###############################################################################
# Define critical pipeline configuration and decisions, roughly equivalent to
# previous inst/targets/targets_critical.R

###############################################################################
# Date range controls all time-related objects for the entire pipeline. This
# is the only target that needs to be chagne to update the pipeline with a new
# temporal range. Relevant months and years are are derived from the explicilty
# defined date range.
chr_daterange:
  start: "2021-12-30"
  end: "2022-01-02"
