###############################################################################
# BEETHOVEN Snakemake configuration (dev)
# 02 October 2026
# Mitchell Manware

###############################################################################
# Define critical pipeline configuration and decisions, roughly equivalent to
# previous inst/targets/targets_critical.R

###############################################################################
# Date range controls all time-related objects for the entire pipeline. This
# is the only target that needs to be chagne to update the pipeline with a new
# temporal range. Relevant months and years are are derived from the explicilty
# defined date range.
chr_daterange:
  start: "2021-12-01"
  end: "2022-01-31"

###############################################################################
# Buffer radii define the buffer distances, in meters, for covariate
# calculations at all AQS model fitting and H3 grid prediction locations.
# Buffer radii are 1000 (1km), 5000 (5km), and 10,000 (10km).
int_radii:
  - 1000
  - 5000
  - 10000
